name: Docs

on:
  push:
    branches:
      - 'docs-*'

jobs:
  Publish_Docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8" ]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install SWIG
        run: sudo apt-get install swig
      - name: Generate C++ wrapper code
        run: |
          cd stag
          swig -c++ -python -verbose stag_internal.i
          cd ..
      - name: Build Python package
        run: python setup.py build_ext --inplace
      - name: Build docs
        run: |
          cd docs
          make html SPHINXOPTS="-W"
          cd ..
      - name: Publish docs
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.WEBSITE_SSH_DEPLOY_KEY }}
        with:
          source-directory: '_build/html'
          destination-github-username: 'staglibrary'
          destination-repository-name: 'stagorg.github.io'
          user-email: macgregor.pr@gmail.com
          target-branch: master
          target-directory: docs/python
