name: Docs

on:
  push:
    branches:
      - 'docs-*'

jobs:
  Publish_Docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8" ]
    steps:
      - name: Install Doxygen
        run: |
          wget https://www.doxygen.nl/files/doxygen-1.9.6.linux.bin.tar.gz
          tar xzvf doxygen-1.9.6.linux.bin.tar.gz
          sudo cp doxygen-1.9.6/bin/doxygen /usr/bin/doxygen
          sudo chmod +x /usr/bin/doxygen
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build docs
        run: |
          cd docs
          chmod +x py_filter
          doxygen
          cd ..
      - name: Publish docs
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.WEBSITE_SSH_DEPLOY_KEY }}
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        with:
          source-directory: 'docs/docs/html'
          destination-github-username: 'staglibrary'
          destination-repository-name: 'stagorg.github.io'
          user-email: macgregor.pr@gmail.com
          target-branch: master
          target-directory: ${{ format('docs/python/{0}', env.BRANCH_NAME) }}
