name: Python package build

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install SWIG
      run: sudo apt-get install swig
    - name: Generate C++ wrapper code
      run: |
        cd stag
        swig -c++ -python -verbose stag_internal.i
        cd ..
    - name: Build manylinux Python wheels
      uses: RalfG/python-wheels-manylinux-build@v0.5.0-manylinux2014_x86_64
      with:
        python-versions: 'cp36-cp36m cp37-cp37m'
    - uses: actions/upload-artifact@master
      with:
        name: manylinux-wheel
        path: dist/*-manylinux*.whl
