name: Benchmark
on:
  push:
    branches:
      - master
      - performance-tests
jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install SWIG
        run: sudo apt-get install swig
      - name: Generate C++ wrapper code
        run: |
          cd stag
          swig -c++ -python -verbose stag_internal.i
          cd ..
      - name: Build Python package
        run: python setup.py build_ext --inplace
      - name: Run performance tests
        run: |
          cd test
          python -m pytest test_performance.py --benchmark-json output.json
          cd ..
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Performance Tests
          tool: 'pytest'
          output-file-path: test/output.json
          github-token: ${{ secrets.STAG_PAT }}
          auto-push: true
          alert-threshold: '130%'
          comment-on-alert: true
          fail-on-alert: true
